// Code generated by mockery v2.39.1. DO NOT EDIT.

package bobber

import mock "github.com/stretchr/testify/mock"

// MockWebsocketService is an autogenerated mock type for the WebsocketService type
type MockWebsocketService struct {
	mock.Mock
}

type MockWebsocketService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsocketService) EXPECT() *MockWebsocketService_Expecter {
	return &MockWebsocketService_Expecter{mock: &_m.Mock}
}

// AddClient provides a mock function with given fields: _a0
func (_m *MockWebsocketService) AddClient(_a0 Client) {
	_m.Called(_a0)
}

// MockWebsocketService_AddClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClient'
type MockWebsocketService_AddClient_Call struct {
	*mock.Call
}

// AddClient is a helper method to define mock.On call
//   - _a0 Client
func (_e *MockWebsocketService_Expecter) AddClient(_a0 interface{}) *MockWebsocketService_AddClient_Call {
	return &MockWebsocketService_AddClient_Call{Call: _e.mock.On("AddClient", _a0)}
}

func (_c *MockWebsocketService_AddClient_Call) Run(run func(_a0 Client)) *MockWebsocketService_AddClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Client))
	})
	return _c
}

func (_c *MockWebsocketService_AddClient_Call) Return() *MockWebsocketService_AddClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsocketService_AddClient_Call) RunAndReturn(run func(Client)) *MockWebsocketService_AddClient_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function with given fields: request
func (_m *MockWebsocketService) Broadcast(request *Request) {
	_m.Called(request)
}

// MockWebsocketService_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockWebsocketService_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - request *Request
func (_e *MockWebsocketService_Expecter) Broadcast(request interface{}) *MockWebsocketService_Broadcast_Call {
	return &MockWebsocketService_Broadcast_Call{Call: _e.mock.On("Broadcast", request)}
}

func (_c *MockWebsocketService_Broadcast_Call) Run(run func(request *Request)) *MockWebsocketService_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Request))
	})
	return _c
}

func (_c *MockWebsocketService_Broadcast_Call) Return() *MockWebsocketService_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsocketService_Broadcast_Call) RunAndReturn(run func(*Request)) *MockWebsocketService_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function with given fields: _a0
func (_m *MockWebsocketService) DeleteClient(_a0 Client) {
	_m.Called(_a0)
}

// MockWebsocketService_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockWebsocketService_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - _a0 Client
func (_e *MockWebsocketService_Expecter) DeleteClient(_a0 interface{}) *MockWebsocketService_DeleteClient_Call {
	return &MockWebsocketService_DeleteClient_Call{Call: _e.mock.On("DeleteClient", _a0)}
}

func (_c *MockWebsocketService_DeleteClient_Call) Run(run func(_a0 Client)) *MockWebsocketService_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Client))
	})
	return _c
}

func (_c *MockWebsocketService_DeleteClient_Call) Return() *MockWebsocketService_DeleteClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsocketService_DeleteClient_Call) RunAndReturn(run func(Client)) *MockWebsocketService_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// HandleMessages provides a mock function with given fields:
func (_m *MockWebsocketService) HandleMessages() {
	_m.Called()
}

// MockWebsocketService_HandleMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessages'
type MockWebsocketService_HandleMessages_Call struct {
	*mock.Call
}

// HandleMessages is a helper method to define mock.On call
func (_e *MockWebsocketService_Expecter) HandleMessages() *MockWebsocketService_HandleMessages_Call {
	return &MockWebsocketService_HandleMessages_Call{Call: _e.mock.On("HandleMessages")}
}

func (_c *MockWebsocketService_HandleMessages_Call) Run(run func()) *MockWebsocketService_HandleMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsocketService_HandleMessages_Call) Return() *MockWebsocketService_HandleMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsocketService_HandleMessages_Call) RunAndReturn(run func()) *MockWebsocketService_HandleMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebsocketService creates a new instance of MockWebsocketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsocketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsocketService {
	mock := &MockWebsocketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
