// Code generated by mockery v2.39.1. DO NOT EDIT.

package bobber

import mock "github.com/stretchr/testify/mock"

// MockRequestService is an autogenerated mock type for the RequestService type
type MockRequestService struct {
	mock.Mock
}

type MockRequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestService) EXPECT() *MockRequestService_Expecter {
	return &MockRequestService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: request
func (_m *MockRequestService) Add(request Request) (*Request, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *Request
	var r1 error
	if rf, ok := ret.Get(0).(func(Request) (*Request, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(Request) *Request); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Request)
		}
	}

	if rf, ok := ret.Get(1).(func(Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockRequestService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - request Request
func (_e *MockRequestService_Expecter) Add(request interface{}) *MockRequestService_Add_Call {
	return &MockRequestService_Add_Call{Call: _e.mock.On("Add", request)}
}

func (_c *MockRequestService_Add_Call) Run(run func(request Request)) *MockRequestService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Request))
	})
	return _c
}

func (_c *MockRequestService_Add_Call) Return(_a0 *Request, _a1 error) *MockRequestService_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_Add_Call) RunAndReturn(run func(Request) (*Request, error)) *MockRequestService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function with given fields:
func (_m *MockRequestService) DeleteAll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestService_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockRequestService_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
func (_e *MockRequestService_Expecter) DeleteAll() *MockRequestService_DeleteAll_Call {
	return &MockRequestService_DeleteAll_Call{Call: _e.mock.On("DeleteAll")}
}

func (_c *MockRequestService_DeleteAll_Call) Run(run func()) *MockRequestService_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestService_DeleteAll_Call) Return(_a0 error) *MockRequestService_DeleteAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestService_DeleteAll_Call) RunAndReturn(run func() error) *MockRequestService_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: id
func (_m *MockRequestService) DeleteById(id string) (*Request, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 *Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Request, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *Request); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRequestService_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id string
func (_e *MockRequestService_Expecter) DeleteById(id interface{}) *MockRequestService_DeleteById_Call {
	return &MockRequestService_DeleteById_Call{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRequestService_DeleteById_Call) Run(run func(id string)) *MockRequestService_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRequestService_DeleteById_Call) Return(_a0 *Request, _a1 error) *MockRequestService_DeleteById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_DeleteById_Call) RunAndReturn(run func(string) (*Request, error)) *MockRequestService_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *MockRequestService) GetAll() ([]*Request, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*Request
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*Request, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Request)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRequestService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRequestService_Expecter) GetAll() *MockRequestService_GetAll_Call {
	return &MockRequestService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRequestService_GetAll_Call) Run(run func()) *MockRequestService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRequestService_GetAll_Call) Return(_a0 []*Request, _a1 error) *MockRequestService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetAll_Call) RunAndReturn(run func() ([]*Request, error)) *MockRequestService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: id
func (_m *MockRequestService) GetById(id string) (*Request, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Request, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *Request); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestService_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockRequestService_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id string
func (_e *MockRequestService_Expecter) GetById(id interface{}) *MockRequestService_GetById_Call {
	return &MockRequestService_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *MockRequestService_GetById_Call) Run(run func(id string)) *MockRequestService_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRequestService_GetById_Call) Return(_a0 *Request, _a1 error) *MockRequestService_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestService_GetById_Call) RunAndReturn(run func(string) (*Request, error)) *MockRequestService_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function with given fields: method, path
func (_m *MockRequestService) Match(method string, path string) (string, string, string) {
	ret := _m.Called(method, path)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 string
	var r1 string
	var r2 string
	if rf, ok := ret.Get(0).(func(string, string) (string, string, string)); ok {
		return rf(method, path)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(method, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(method, path)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) string); ok {
		r2 = rf(method, path)
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

// MockRequestService_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockRequestService_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - method string
//   - path string
func (_e *MockRequestService_Expecter) Match(method interface{}, path interface{}) *MockRequestService_Match_Call {
	return &MockRequestService_Match_Call{Call: _e.mock.On("Match", method, path)}
}

func (_c *MockRequestService_Match_Call) Run(run func(method string, path string)) *MockRequestService_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRequestService_Match_Call) Return(namespaceID string, endpointID string, response string) *MockRequestService_Match_Call {
	_c.Call.Return(namespaceID, endpointID, response)
	return _c
}

func (_c *MockRequestService_Match_Call) RunAndReturn(run func(string, string) (string, string, string)) *MockRequestService_Match_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestService creates a new instance of MockRequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestService {
	mock := &MockRequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
